config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  # get '/wikis/:wiki_id/collaborators/:id', to: 'collaborators#destroy'
  get 'downgrade', to:  'users#downgrade'

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  resources :users, only: [:show, :index]
  root to: 'wikis#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  after_initialize :set_role

  def set_role
    self.role ||= :standard
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

  has_many :wikis 

  enum role: [:standard, :premium, :admin]

  def expose_wikis
    self.wikis.update_all(private: false)
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :collaborating_users, through: :collaborators, source: :user
  scope :public_wikis, -> { where(private: false) }

  before_create :set_private

  private

  def set_private
    self.private ||= false;
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


private

  def require_sign_in
    unless current_user
      flash[:alert] = "You must be logged in to do that"
      redirect_to new_session_path
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || wikis_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
  # Creates a Stripe Customer object, for associating
  # with the charge
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )

  # Where the real magic happens
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is NOT the user_id in your app
    amount: 10_00,
    description: "Premium Membership - #{current_user.email}",
    currency: 'usd'
  )

  if current_user.role == "standard"
    current_user.update_attribute(:role, 'premium')
    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to user_path(current_user) # or wherever
  else
    redirect_to user_path(current_user)
  end

  # Stripe will send back CardErrors, with friendly messages
  # when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "BigMoney Membership - #{current_user}",
    amount: 10_00
  }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @collaborator = Collaborator.new(user_id: params[:collaborator][:user_id], wiki_id: params[:wiki_id])
    @wiki = Wiki.find(params[:wiki_id])

    if @collaborator.save
      flash[:notice] = "#{@collaborator.user.email} has been added as a collaborator to #{@wiki.title}"
    else
      flash[:error] = "Adding collaborator failed"
    end
      # redirect_to @wiki
      redirect_to proc { edit_wiki_url(@wiki) }
  end

  def destroy
    # @collaborator = Collaborator.find(user_id: params[:collaborator][:user_id], wiki_id: params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])

    if @collaborator.destroy
      flash[:notice] = "#{@collaborator.user.email} has been removed from #{@wiki.title}."
    else
      flash[:error] = "Removing collaborator failed"
    end
      redirect_to proc { edit_wiki_path(@wiki) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def downgrade
    current_user.update_attribute(:role, 'standard')
    current_user.expose_wikis
    flash[:notice] = "#{current_user.email} you're account has been downgraded"
    redirect_to wikis_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @collaborator = Collaborator.new
    @collab_ids = @wiki.collaborators.map(&:user_id)
    @noncollaborators = User.all.select{ |user| user != @wiki.user || !@collab_ids.include?(user.id) }
  end

  def destroy
    @wiki = Wiki.where(id: params[:id]).first
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
 end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def owner
    owner = @wiki.user
  end

  def authorize_user(wiki)
    if current_user != wiki.user || current_user != admin || current_user
      flash[:alert] = "I am sorry but you do not have the permissions to do that."
      redirect_to wikis_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {filter_html: true, hard_wrap: true, space_after_headers: true, fenced_code_blocks: true, prettify: true}
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer)
    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="col-lg-12">
  <%= form_tag charges_path do %>
    <h4>Click to upgrade your account!</h4> </br>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="Premium is just a step away!" ></script>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico|Quattrocento rel="stylesheet" type="css/text">
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li>
          <%= link_to "Blocipedia", user_signed_in? ? wikis_path : root_path %>
        </li>
        <div class="pull-right user-info">
          <% if user_signed_in? %>
            <strong><%= link_to current_user.email, user_path(current_user), :class => 'navbar-link' %></strong> |
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
        </div>
      </ul>
      <% if flash[:notice] %>
        <div class='alert alert-success'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class='alert alert-danger'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class='alert alert-warning'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> Welcome to Premium, Blochead!</h1>
    <p class="lead">Now that you have become a Blochead you can now take full advantage
      of what comes with membership!</p>
      <hr class="my-4">
      <ul>
        <li>All access to wikis</li>
        <li>A long lasting relationship with the founder</li>
        <li>An updated email list of our new members so you can network</li>
        <li>Find out who the next Blocheads are!</li>
        <li>Forever consider yourself a Blochead</li>
      </ul> </br>

  <div class="col-md-4">
    <%= link_to "Access Wikis", wikis_path, class: 'btn btn-primary btn-lg' %>
  </div> </br>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"> Hello! Welcome to Blocipedia! </h1>
  <h3>Sign up and join in the fun!</h3>
  <hr class="my-4">

  <div class="col-4">
    <%= link_to "Standard Membership", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/wikis/_collaborator.html.erb
<% if @wiki.user == current_user && current_user.premium? %>
  <%= form_for @collaborator, url: wiki_collaborators_path(@wiki) do |f| %>
    <div class="form-group">
       <%= f.label :collaborators %>
       <%= f.select :user_id, [], {} do %>
         <% @noncollaborators.each do |user| %>
           <% if user != current_user && user.id != collaborator.user_id %>
             <%= content_tag :option, user.email, value: user.id %>
           <% end %>
         <% end %>
       <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "Add Collaborator", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group" style="margin-left: 20px;">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private Wiki
      <% end %>
    </div>
    <%= f.text_field 'wiki_id', value: @wiki.id, hidden: true %>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wiki</p>
    <ul>
      <li>No racial slurs.</li>
      <li>Don't post unintelligible subjects.</li>
      <li>The incessant use of stupid wikis will get you banned.</li>
    </ul>
    <% @wiki.collaborators.each do |c| %>
      <%= c.user.email %>
      <%= link_to "x", wiki_collaborator_path(@wiki, c), :method => :delete %> <br />
    <% end %>
  </div>


  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <br />
    <%= render partial: 'collaborator', locals: { collaborator: @collaborator } %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Checkout the Wikis!</h1>
  <p class="lead">This is where you can view the wikis that have
  been created! Take a gander or upgrade your account to Premium to take
full advantage of what Blocipedia truly offers!</p>
  <hr class="my-4">
  <% if current_user.role == "standard" %>
    <%= link_to "Upgrade", new_charge_path, class: 'btn btn-success btn-lg' %>
  <% else %>
    <%= link_to "Downgrade", downgrade_path, class: 'btn btn-danger btn-lg', data: {confirm: 'If you downgrade, your private wikis will become public! Are you sure you would like to continue?'} %>
  <% end %>
</div>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to markdown(wiki.title), wiki_path(wiki.id) %>
      </h4>
    </div>
  </div>
<% end %>

<div class="col-lg" style="margin-top: 1.2em;">
  <%= link_to "New", new_wiki_path, class: 'btn btn-primary' %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wiki</p>
    <ul>
      <li>No racial slurs.</li>
      <li>Don't post unintelligible subjects.</li>
      <li>The incessant use of stupid wikis will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<%= markdown(@wiki.title) %>

<div class="row">
  <div class="col-md-8">
    <%= markdown(@wiki.body) %>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>